#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Customize to your needs...
source ~/Documents/repos/clario/dev-helpers/ninja-sa/ninja_cloud_sa.sh

export JAVA_HOME=`/usr/libexec/java_home -v 11`
export DEV_HELPERS_HOME=/Users/sprivers/Documents/repos/clario/dev-helpers

alias sammy='$DEV_HELPERS_HOME/sammy/sammy.sh'
alias clario='cd /Users/sprivers/Documents/repos/clario'

switch-creds dev

export PATH="$HOME/.pyenv/bin:/Users/sprivers/homebrew/bin:$PATH"
eval "$(pyenv init --path)"
eval "$(pyenv virtualenv-init -)"

export NVM_DIR="$HOME/.nvm"
  [ -s "/Users/sprivers/homebrew/opt/nvm/nvm.sh" ] && . "/Users/sprivers/homebrew/opt/nvm/nvm.sh" 
  [ -s "/Users/sprivers/homebrew/opt/nvm/etc/bash_completion.d/nvm" ] && . "/Users/sprivers/homebrew/opt/nvm/etc/bash_completion.d/nvm" 

export GROOVY_HOME=/Users/sprivers/homebrew/opt/groovy/libexec

# The next line updates PATH for the Google Cloud SDK.
if [ -f '/Users/sprivers/google-cloud-sdk/path.zsh.inc' ]; then . '/Users/sprivers/google-cloud-sdk/path.zsh.inc'; fi

# The next line enables shell command completion for gcloud.
if [ -f '/Users/sprivers/google-cloud-sdk/completion.zsh.inc' ]; then . '/Users/sprivers/google-cloud-sdk/completion.zsh.inc'; fi

function switch-repoman-settings() {
  if [[ $1 == "on" ]]
  then
    ln -sf ~/.m2/settings.xml.repoman ~/.m2/settings.xml
  else
    ln -sf ~/.m2/settings.xml.clario ~/.m2/settings.xml
  fi  
  ll ~/.m2/settings.xml
}

#THIS MUST BE AT THE END OF THE FILE FOR SDKMAN TO WORK!!!
export SDKMAN_DIR="$HOME/.sdkman"
[[ -s "$HOME/.sdkman/bin/sdkman-init.sh" ]] && source "$HOME/.sdkman/bin/sdkman-init.sh"
