#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Customize to your needs...
source ~/Documents/repos/clario/dev-helpers/ninja-sa/ninja_cloud_sa.sh

export JAVA_HOME=`/usr/libexec/java_home -v 11`
export DEV_HELPERS_HOME=/Users/sprivers/Documents/repos/clario/dev-helpers

alias sammy='$DEV_HELPERS_HOME/sammy/sammy.sh'

switch-creds dev

export PATH="$HOME/.pyenv/bin:/Users/sprivers/homebrew/bin:$PATH"
eval "$(pyenv init --path)"
eval "$(pyenv virtualenv-init -)"

export NVM_DIR="$HOME/.nvm"
  [ -s "/Users/sprivers/homebrew/opt/nvm/nvm.sh" ] && . "/Users/sprivers/homebrew/opt/nvm/nvm.sh" 
  [ -s "/Users/sprivers/homebrew/opt/nvm/etc/bash_completion.d/nvm" ] && . "/Users/sprivers/homebrew/opt/nvm/etc/bash_completion.d/nvm" 
